### ISSUE TITLE
Failing start of the docker container

### ISSUE THREAD

**Issue by lukas-vlcek** [BitScoutOrg/docker-fluentd#20]
```
Lukass-MacBook-Pro:docker-fluentd lvlcek$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
9bf1fdd09480        19b97c4fc6d7        "/bin/sh -c /usr/sbin"   5 minutes ago       Exited (1) 5 minutes ago                       suspicious_pasteur
```

I am trying to start this container on my Mac using docker-machine (but using Mac and docker-machine should not make any difference IMO). I will investigate further, just in case anybody has any idea what might be wrong...

```
Lukass-MacBook-Pro:docker-fluentd lvlcek$ docker logs --tail 200 9bf1fdd09480a56d2ae4869d2755b9774f30b7e040ecb815d0dbedd0c854477e
+ ES_HOST=viaq-elasticsearch
+ ES_PORT=9200
+ SYSLOG_LISTEN_PORT=10514
+ DEBUG_FLUENTD=false
+ LOGSTASH_PREFIX=v2016.03.10.0-viaq
+ '[' false = true ']'
+ FLUENTD_ARGS=
+ '[' -f /data/fluent.conf ']'
+ for file in /etc/fluent/fluent.conf '/etc/fluent/config.d/*.conf' '/etc/fluent/config.d/**/*.conf'
+ '[' '!' -f /etc/fluent/fluent.conf ']'
+ continue
+ for file in /etc/fluent/fluent.conf '/etc/fluent/config.d/*.conf' '/etc/fluent/config.d/**/*.conf'
+ '[' '!' -f '/etc/fluent/config.d/*.conf' ']'
+ continue
+ for file in /etc/fluent/fluent.conf '/etc/fluent/config.d/*.conf' '/etc/fluent/config.d/**/*.conf'
+ '[' '!' -f '/etc/fluent/config.d/**/*.conf' ']'
+ continue
+ fluentd
2016-06-06 12:36:42 +0000 [info]: reading config file path="/etc/fluent/fluent.conf"
/opt/app-root/src/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:474:in `read': No such file or directory - /etc/fluent/fluent.conf (Errno::ENOENT)
    from /opt/app-root/src/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:474:in `read_config'
    from /opt/app-root/src/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:144:in `start'
    from /opt/app-root/src/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /opt/app-root/src/gems/fluentd-0.12.26/bin/fluentd:5:in `<top (required)>'
    from /opt/app-root/src/bin/fluentd:23:in `load'
    from /opt/app-root/src/bin/fluentd:23:in `<main>'
```

**Comment by lukas-vlcek** [comment]
Hmmm... I am getting the same on Fedora too. This might be related to my recent PR... I will check.

**Comment by lukas-vlcek** [comment]
Probably not related to my recent PR. I tried to build the image from older commits and still running into this issue (now on Fedora):

```
[lvlcek@dhcp-2-178 docker-fluentd]$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
484ecc2e21a5        17cf1ebcc25a        "/bin/sh -c /usr/sbin"   12 seconds ago      Exited (1) 5 seconds ago                       jolly_bartik

[lvlcek@dhcp-2-178 docker-fluentd]$ docker logs --tail 200 484ecc2e21a5181489727d143dd2571275c1deb837d9774908b9057d22fb6a56
+ ES_HOST=viaq-elasticsearch
+ ES_PORT=9200
+ SYSLOG_LISTEN_PORT=10514
+ DEBUG_FLUENTD=false
+ LOGSTASH_PREFIX=v2016.03.10.0-viaq
+ '[' false = true ']'
+ FLUENTD_ARGS=
+ '[' -f /data/fluent.conf ']'
+ for file in /etc/fluent/fluent.conf '/etc/fluent/config.d/*.conf' '/etc/fluent/config.d/**/*.conf'
+ '[' '!' -f /etc/fluent/fluent.conf ']'
+ continue
+ for file in /etc/fluent/fluent.conf '/etc/fluent/config.d/*.conf' '/etc/fluent/config.d/**/*.conf'
+ '[' '!' -f '/etc/fluent/config.d/*.conf' ']'
+ continue
+ for file in /etc/fluent/fluent.conf '/etc/fluent/config.d/*.conf' '/etc/fluent/config.d/**/*.conf'
+ '[' '!' -f '/etc/fluent/config.d/**/*.conf' ']'
+ continue
+ fluentd
2016-06-06 13:23:32 +0000 [info]: reading config file path="/etc/fluent/fluent.conf"
/opt/app-root/src/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:474:in `read': No such file or directory - /etc/fluent/fluent.conf (Errno::ENOENT)
    from /opt/app-root/src/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:474:in `read_config'
    from /opt/app-root/src/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:144:in `start'
    from /opt/app-root/src/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:73:in `require'
    from /opt/app-root/src/gems/fluentd-0.12.26/bin/fluentd:5:in `<top (required)>'
    from /opt/app-root/src/bin/fluentd:23:in `load'
    from /opt/app-root/src/bin/fluentd:23:in `<main>'

[lvlcek@dhcp-2-178 docker-fluentd]$ git log --oneline -n 5
c5dca58 Merge pull request #16 from t0ffel/master
47f9ca2 Merge pull request #18 from lukas-vlcek/17
c862389 Specify fluentd version. Closes #17
ab10d44 Move LOGSTASH_PREFIX to env variables, normalizer info parametrization added
36e59a1 cleanup of the configs and scripts. Added instructions
```

**Comment by lukas-vlcek** [comment]
It seems this issue was introduced by merging https://github.com/ViaQ/docker-fluentd/pull/16
When I use commit f1ab463 and manually fix Dockerfile (to workaround issue fixed later, see https://github.com/ViaQ/docker-fluentd/issues/17) then the container starts and run correctly.

**Comment by richm** [comment]
How are you running fluentd?

**Comment by lukas-vlcek** [comment]
Basically I delete all docker containers, images and then I do:

```
./build-image.sh
docker create _hash_
docker start _hash_
```
